trigger: none

jobs:
  - job: azure
    pool:
     vmImage: ubuntu-latest
    steps:
      - script: echo "Hi from Microsoft Agent!"
      - script: echo "The last command was $?"
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'wget https://download.agent.dev.azure.com/agent/4.266.2/vsts-agent-linux-x64-4.266.2.tar.gz'

  - job: hosted
    pool:
     name: default
    steps:
      - script: echo "Hi from Self Agent!"
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'wget https://download.agent.dev.azure.com/agent/4.266.2/vsts-agent-linux-x64-4.266.2.tar.gz'
    