trigger: none

jobs:
  - job: azure
    pool:
     vmImage: ubuntu-latest
    dependsOn: []
    steps:
      - script: echo "Hi from Microsoft Agent!"
      - script: echo "The last command was $?"

  - job: hosted
    pool:
     name: default
    dependsOn: []
    steps:
      - script: echo "Hi from Self Agent!"
    