trigger: none

jobs:
  - job: azure
    pool:
     vmImage: ubuntu-latest
    dependsOn: []
    steps:
      - script: echo "Hi from Microsoft Agent!"
  - job: hosted
    pool:
     name: default
    dependsOn: []
    steps:
      - script: echo "Hi from Self Agent!"
    